// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blogs_section: dynamic(() => import("./BlogsSection")),
  brand_section: dynamic(() => import("./BrandSection")),
  cards_section: dynamic(() => import("./CardsSection")),
  contact_form: dynamic(() => import("./ContactForm")),
  content: dynamic(() => import("./Content")),
  frequently_asked_questions: dynamic(() =>
    import("./FrequentlyAskedQuestions")
  ),
  header_section: dynamic(() => import("./HeaderSection")),
  home_component: dynamic(() => import("./HomeComponent")),
  news_section: dynamic(() => import("./NewsSection")),
  team_section: dynamic(() => import("./TeamSection")),
};
